[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["core"]

[project]
name = "no-intro-rom-checkr"
description = "A CLI tool to check ROMs against the No-Intro database."
version = "2026.5.22"
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["rom", "check", "no-intro", "cli", "tool"]
authors = [
    { name = "jordan95v", email = "90615280+jordan95v@users.noreply.github.com" },
]
maintainers = [
    { name = "jordan95v", email = "90615280+jordan95v@users.noreply.github.com" },
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["lxml>=6.0.2", "typer>=0.24.1"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-env>=1.6.0",
    "pytest-mock>=3.15.1",
    "python-dotenv>=1.2.2",
    "types-lxml>=2026.2.16",
]

[tool.pytest.ini_options]
addopts = "-vv --tb=short --cov=core --cov-report=term-missing"

[tool.coverage.run]
omit = ["**/__init__.py", "**/tests/*"]
